# Streamlit Secrets Configuration
# For Streamlit, secrets should be at the top level (no [secrets] section)

# Use environment variable for Gemini API key
# The GEMINI_KEY environment variable is set by Cloud Run via --set-secrets
GEMINI_API_KEY = "env:GEMINI_KEY"

# How to get your Gemini API key:
# 1. Go to https://aistudio.google.com/app/apikey
# 2. Sign in with your Google account
# 3. Click "Create API Key"
# 4. Store the key in Google Secret Manager as 'gemini_key'
# 5. Cloud Run will automatically mount it as GEMINI_KEY environment variable

# Note: The API key is now stored securely in Google Secret Manager! 