# Streamlit Secrets Configuration
# For Streamlit, secrets should be at the top level (no [secrets] section)

# Use environment variable for Gemini API key
GEMINI_API_KEY = "${GEMINI_KEY}"

# How to get your Gemini API key:
# 1. Go to https://aistudio.google.com/app/apikey
# 2. Sign in with your Google account
# 3. Click "Create API Key"
# 4. Store the key in Google Secret Manager as 'gemini-api-key'
# 5. The key will be automatically injected as GEMINI_KEY environment variable

# Note: The API key is now stored securely in Google Secret Manager! 