# Streamlit Secrets Configuration

# For local development, uncomment and add your key:
# GEMINI_API_KEY = "your-actual-gemini-api-key-here"

# For Cloud Run deployment, use environment variables directly in your Python code:
# import os
# api_key = os.environ.get("GEMINI_API_KEY")

# Note: The "env:VARIABLE_NAME" syntax does NOT work in secrets.toml

# How to get your Gemini API key:
# 1. Go to https://aistudio.google.com/app/apikey
# 2. Sign in with your Google account  
# 3. Click "Create API Key"
# 4. For Cloud Run: Store in Google Secret Manager as 'gemini_key'
# 5. For local: Add directly to this file (and add to .gitignore) 